name: Run E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Install wait-on
        run: npm install --save-dev wait-on

      # Поднимаем сервер в фоне
      - name: Start local server
        run: npm run start-server &

      # Ждём, пока сервер будет доступен
      - name: Wait for server
        run: npx wait-on http://localhost:8080/form.html

      # Запускаем тесты
      - name: Run Playwright E2E tests
        run: npx playwright test --reporter=html --project=chromium --project=firefox

      # Генерируем Allure отчёт
      - name: Generate Allure report
        run: npm run allure:generate
    
      - name: Сохранение HTML отчёта
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
      - name: Публикация отчёта на GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report